jwt:
  secret: ${JWT_SECRET} # JWT 암호화 키
  access-token-expire-time: 2592000000 # 엑세스 토큰 만료 시간 (30일)
  refresh-token-expire-time: 2592000000 # 리프레시 토큰 만료 시간 (30일)

springdoc:
  packages-to-scan: org.farmsystem.homepage
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger  # Swagger UI 접근 경로
    disable-swagger-default-url: true  # 기본 Swagger UI 문서 숨김
    display-request-duration: true  # 요청 시간 표시
    operations-sorter: alpha  # API 정렬 방식 (알파벳 순)

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true  
